services:
  # Consul
  consul:
    image: hashicorp/consul
    ports:
      - '8500:8500'

  # patroni
  patroni:
    build: .
    image: nomad-pgsql-patroni:17.4-1.tsdb_gis
    environment:
      PGDATA: /alloc/data
    ports:
      - '5433:5432'
      - '8008:8008'
    tmpfs:
      - /alloc
    volumes:
      - './example-patroni.yml:/secrets/patroni.yml'
